### ISSUE TITLE
object creation context crash

### ISSUE THREAD

**Issue by ramagottfried** [HfMT-ZM4/libo#1]
woot!
first issue on the fork!

evaluating this crashes for me on the error reporting callback, my guess is that the context pointer isn't making it? (haven't looked at the code)

<pre><code>
----------begin_max5_patcher----------
448.3ocmTFzSyCCCF9b6uhnbk90sVPeLPhqbhCbmgpxR8XYzkDklBYLs+6j3
1BpiRQPOrN6733W6M6CwQzUJGTSIWSdfDEcHNJBcEbD0YGQ2wb7JVMhQUofS
aR4pRH.lzhXAmEOd1ZkhbC4vRI4jmYR3UOwR5SKoIibLlBDXlTYgJgDFGTT5
oloVsM0+0QuoMhpRCHCU0WON7bXb2CjIWX3UiKgQzbPxa.V4z7FOaOYggUJZ
pm752640BWgVX4aJzpooccz0VlwRN6zLMdnGS96snu82nQZPkMFlUnj28iw3
xFTGSgtO62zfb4czfrbxaM+za8aZce08iCccre9Hzo3pFINjjm24UafZPZw9
RwPjy6QXdIHjOUX.tscN8xEWkNOgje0hvqKxyBuNOyaQdrKJYyNgrBr3HaVm
y0JocMiCAey+DT0X6I60knrcTe01+cQeEzhY2qgVUPusop5dF+YvRSFX8gJB
IrV7FFPVd57f2iwwgOPFJSqeAL09pGW3DV23W1rUYBlKRPSgr0DqBpAdQzyi
0.kY78Gqu4zXvDQc+uUyzc9UTFYi.iN1mzPJw+PJY6fZcWq.22EeL9c.FpJK
JC
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
I don't get a crash, but it prints "error evaluating expression:" with no info about the expression. Can you pull everything, build and try again?

**Comment by ramagottfried** [comment]
hmm, yeah, just updated, but still crashes when I click on the box

Process:               Max [15864]
Path:                  /Applications/Max.app/Contents/MacOS/Max
Identifier:            com.cycling74.Max
Version:               8.1.0 [5096a10] (8.1.0)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Max [15864]
User ID:               501

Date/Time:             2019-09-09 20:34:09.724 +0200
OS Version:            Mac OS X 10.14.6 (18G95)
Report Version:        12
Bridge OS Version:     3.6 (16P6571)
Anonymous UUID:        1A1C482F-4F53-DB9C-9CE7-29639C350D39

Sleep/Wake UUID:       13260787-2E99-4AE1-9851-8B52B933349C

Time Awake Since Boot: 81000 seconds
Time Since Wake:       560 seconds

System Integrity Protection: enabled

Crashed Thread:        0  CrBrowserMain  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000100
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [15864]

VM Regions Near 0x100:
--> 
    __TEXT                 00000001036d9000-0000000104313000 [ 12.2M] r-x/rwx SM=COW  /Applications/Max.app/Contents/MacOS/Max

Thread 0 Crashed:: CrBrowserMain  Dispatch queue: com.apple.main-thread
0   libsystem_platform.dylib      	0x00007fff6c5236f2 _platform_strlen + 18
1   edu.cnmat.berkeley.o.expr.codebox	0x000000010d18987a omax_util_liboErrorHandler + 42
2   edu.cnmat.berkeley.o.expr.codebox	0x000000010d15f09d osc_error_handler + 733
3   edu.cnmat.berkeley.o.expr.codebox	0x000000010d1704a7 osc_expr_specFunc_assign + 855
4   edu.cnmat.berkeley.o.expr.codebox	0x000000010d16c472 osc_expr_evalInLexEnv + 1122
5   edu.cnmat.berkeley.o.expr.codebox	0x000000010d16c009 osc_expr_eval + 41
6   edu.cnmat.berkeley.o.expr.codebox	0x000000010d158c6e oexprcodebox_fullPacket + 366
7   edu.cnmat.berkeley.o.expr.codebox	0x000000010d15903b oexprcodebox_mouseup + 107
8   com.cycling74.Max             	0x000000010385cfcc BoxComponent::sendMouseMessage(juce::MouseEvent const&, symbol*) + 582
9   com.cycling74.Max             	0x000000010385e643 BoxComponent::mouseUp(juce::MouseEvent const&) + 525
10  com.cycling74.Max             	0x0000000103f2872c juce::MouseInputSourceInternal::setButtons(juce::Point<float>, juce::Time, juce::ModifierKeys) + 684

**Comment by maccallum** [comment]
fixed in the experimental branch (no issue in the main branch)
