### ISSUE TITLE
getbundlemember second value as OSC address (not string)

### ISSUE THREAD

**Issue by ramagottfried** [HfMT-ZM4/libo#10]
according to the docs, the second arg of gbm is supposed be able to be an osc address, but it seems that it doesn't work (I found out after a looooong time debugging).

this fails:

```
/bundle = {
  /foo : 1
},
/addr = "/foo",
/bar = getbundlemember(/bundle, /addr)
```

value() does work as expected.

test patch:

<pre><code>
----------begin_max5_patcher----------
551.3oc2V07aaBCE+L7WAxmZkXI.I7wpTt1y69XpxAdoycfMxXhRWT9ee3mc
VoIj1nnlpocIl2im8y92Glr00grTrAZId248cOGmstNNXJcBGarColtonh1h
kQDSJYsMUzmI9l2pfMJ7MSW1wKqf9G2lyyUSWID8OGly24mymRKKk8g4Dc9b
hN0RpNS39EphwgBQGGWsXaxFIzBbEUwD7GFuBpp3mL9iOHgBk4jDGmLIv2KJ
atdHLNPOjkMIv6G1Iw6pY7JPgmoPaxUBtZEs.z4BdoPQm5vJYkFrX4SeIc+1
2Tl54FvrIHj+1M8B2x9M9hvnIA5r6bc0+3e1vNroQNoPTB5BOE1uPi8ddig8
KNB6W38HnLSrFpWBxarKiu2ZZUGbCNwau8BInj2kfBSyzCylEiDTxoHnnylf
lcLAkcRB59tppuQK9EnH9uQzGKMdf6YDvIJIxndyFndmM+pndS9rTum7RCqR
8BthX1ogvTTPEkDN.A0AWADL9+R+uw4egF+z2UaGlEM3B5qjwe9+VF+2l+zD
1hA1fwXqgWJeYNBKtacDwe8pf6geF3NVCd5O3eufmcc9WSFshNYw98g8yBdu
b5KgVEiiZ4A0jZpYT59b6y7ynOIe.8I7L5S7Q8w.izll0fr0VL1hd06SBoNL
yGCYbSHdEHQBqY6qGk.DprWxo50acRbaQ1jXLfj5dMuj2wvY6pOb8sDcFbZM
z1X0WnAxcm6e.X0NddO
-----------end_max5_patcher-----------
</code></pre>

**Comment by maccallum** [comment]
this works as expected. the second argument is not resolved in the context of the working bundle, but rather the bundle found in the first argument. if i'm missing something, feel free to reopen
