### ISSUE TITLE
print()

### ISSUE THREAD

**Issue by ramagottfried** [HfMT-ZM4/libo#8]
would be very useful to have a print function for debugging

**Comment by ramagottfried** [comment]
much nicer than having to break expressions apart and use o.select all the time

**Comment by maccallum** [comment]
ok yeah, i think this is possible due to the context object we're passing around. i'll add this to the queue

**Comment by maccallum** [comment]
o.expr.codebox now has a print function. it takes strings that can be concatenated together with the `+` operator, and multiple arguments are printed to separate lines. it also returns a list of all the strings it printed. cc4f0b8fa3b2519bab3f3d884f058bcacfbcae29

**Comment by maccallum** [comment]
i also added a `line()` function that returns the line number from which the function was called.

**Comment by ramagottfried** [comment]
super cool!
